export { default as ScoresGlobal } from './ScoreGlobal'
export { default as ScoresIndicator1 } from './Score1'
export { default as ScoresIndicator2 } from './Score2'
export { default as ScoresIndicator3 } from './Score3'
export { default as ScoresIndicator4 } from './Score4'
export { default as ScoresIndicator5 } from './Score5'
